name: Run Python Script

on:
  schedule:
<<<<<<< HEAD
    - cron: "0 5 * * *"
  workflow_dispatch:
=======
    - cron: "0 0 * * 0"
>>>>>>> 44e1d5bc5b1cb80bdcea87d3601a07a9f1bf3a41

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Cache pipenv virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: pipenv install

      - name: Run Python script
        run: pipenv run python new_app.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
<<<<<<< HEAD
          git add .
          git commit -m "Add generated JSON file" || echo "No changes to commit"
          git push
=======
          git add .  
          git commit -m "Add generated HTML file"
          git push origin HEAD
>>>>>>> 44e1d5bc5b1cb80bdcea87d3601a07a9f1bf3a41
